/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRepositories"];
        put?: never;
        post: operations["createRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repositoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRepository"];
        put?: never;
        post?: never;
        delete: operations["deleteRepository"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repositoryId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRuns"];
        put?: never;
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pauseRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRunArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRunReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approvalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approvalId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvalRuns"];
        put?: never;
        /** @description Admin-only import. The server re-grades all three 30-case evidence runs. */
        post: operations["createEvalRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/runs/{evalRunId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvalRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPrompts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts/{agent}/{version}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Admin-only promotion after deterministic regression checks. */
        post: operations["promotePrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts/{agent}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollbackPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "admin" | "operator" | "viewer";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            createdAt: string;
        };
        Session: {
            /** Format: uuid */
            id: string;
            sourceIp: string;
            userAgent: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            idleExpiresAt: string;
            /** Format: date-time */
            revokedAt?: string;
        };
        LoginResponse: {
            user: components["schemas"]["User"];
            session: components["schemas"]["Session"];
            csrfToken: string;
        };
        SessionList: {
            items: components["schemas"]["Session"][];
            /** Format: uuid */
            currentSessionId: string;
        };
        Repository: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerId: string;
            name: string;
            localPath: string;
            defaultBranch: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RepositoryPage: {
            items: components["schemas"]["Repository"][];
            nextCursor?: string;
        };
        /** @enum {string} */
        RunStatus: "created" | "planning" | "waiting_for_plan_approval" | "preparing_workspace" | "implementing" | "evaluating" | "waiting_for_action_approval" | "paused" | "repairing" | "completed" | "failed" | "cancelled";
        RunBudget: {
            maxIterations?: number;
            maxNodeCalls?: number;
            maxModelCalls?: number;
            maxToolCalls?: number;
            /** Format: int64 */
            maxToolOutputBytes?: number;
            maxChangedFiles?: number;
            /** Format: int64 */
            maxDiffBytes?: number;
            maxDiffLines?: number;
            maxRepairs?: number;
            maxInputTokens?: number;
            maxOutputTokens?: number;
            maxEstimatedCostUsd?: number;
            /**
             * Format: int64
             * @description Nanoseconds
             */
            maxDuration?: number;
            nodeCalls?: number;
            estimatedCostUsd?: number;
            modelCalls?: number;
            toolCalls?: number;
            /** Format: int64 */
            toolOutputBytes?: number;
            inputTokens?: number;
            outputTokens?: number;
        };
        PlanStep: {
            id: string;
            description: string;
            acceptanceCriteria: string[];
            dependsOn: string[];
        };
        PlanRisk: {
            /** @enum {string} */
            level: "low" | "medium" | "high";
            description: string;
        };
        ExecutionPlan: {
            summary: string;
            assumptions: string[];
            filesLikelyAffected: string[];
            steps: components["schemas"]["PlanStep"][];
            risks: components["schemas"]["PlanRisk"][];
            testStrategy: string[];
        };
        ImplementationResult: {
            summary: string;
            patch: string;
            changedFiles: string[];
            evidence: string[];
            unresolvedIssues: string[];
            requestedApprovals: string[];
        };
        DiffArtifact: {
            patch: string;
            sha256: string;
            /** Format: int64 */
            size: number;
            changedFiles: string[];
        };
        TestAssessment: {
            toolCallId: string;
            program: string;
            args: string[];
            exitCode: number;
            stdout: string;
            stderr: string;
            /**
             * Format: int64
             * @description Nanoseconds
             */
            duration: number;
            truncated: boolean;
            passed: boolean;
            /** Format: date-time */
            completedAt: string;
        };
        Finding: {
            id: string;
            /** @enum {string} */
            severity: "info" | "low" | "medium" | "high" | "critical" | "blocking";
            file: string;
            line?: number;
            title: string;
            evidence: string;
            recommendation: string;
            failureMode?: string;
            impact?: string;
            confirmed: boolean;
            humanReview?: boolean;
        } & {
            [key: string]: unknown;
        };
        AssessmentResult: {
            summary: string;
            findings: components["schemas"]["Finding"][];
        };
        JudgeDecision: {
            version: string;
            /** @enum {string} */
            action: "pass" | "pass_with_approval" | "repair" | "human_review" | "fail";
            reasons: string[];
            findingIds: string[];
            inputSha256: string;
            /** Format: date-time */
            decidedAt: string;
        };
        ApprovalRequest: {
            /** Format: uuid */
            approvalId: string;
            /** Format: uuid */
            runId: string;
            actionType: string;
            reason: string;
            scope: string[];
            /** @enum {string} */
            risk: "low" | "medium" | "high";
            /** @enum {string} */
            status: "pending" | "approved" | "rejected";
            comment?: string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            resolvedAt?: string;
            toolCallId?: string;
            toolName?: string;
            toolVersion?: string;
            inputSha256?: string;
            workspaceId?: string;
            policyVersion?: string;
        };
        ModelInvocation: {
            agent?: string;
            nodeId?: string;
            provider?: string;
            model?: string;
            promptVersion?: string;
            promptSha256?: string;
            status?: string;
            inputTokens?: number;
            outputTokens?: number;
            /** Format: int64 */
            latencyMilliseconds?: number;
            estimatedCostUsd?: number;
            /** Format: date-time */
            createdAt?: string;
        } & {
            [key: string]: unknown;
        };
        ToolCallAudit: {
            callId?: string;
            nodeId?: string;
            agent?: string;
            toolName?: string;
            toolVersion?: string;
            policyAction?: string;
            policyRuleId?: string;
            status?: string;
            /** Format: int64 */
            outputBytes?: number;
            /** Format: int64 */
            latencyMilliseconds?: number;
            /** Format: date-time */
            createdAt?: string;
        } & {
            [key: string]: unknown;
        };
        Run: {
            /** Format: uuid */
            runId: string;
            /** Format: uuid */
            traceId: string;
            /** Format: uuid */
            ownerId?: string;
            /** Format: uuid */
            repositoryId?: string;
            /** Format: int64 */
            version: number;
            status: components["schemas"]["RunStatus"];
            task: string;
            repositoryPath: string;
            baseRevision: string;
            currentNodeId: string;
            completedNodeIds?: string[];
            plan?: components["schemas"]["ExecutionPlan"];
            implementation?: components["schemas"]["ImplementationResult"];
            diff?: components["schemas"]["DiffArtifact"];
            testAssessment?: components["schemas"]["TestAssessment"];
            reviewResult?: components["schemas"]["AssessmentResult"];
            securityResult?: components["schemas"]["AssessmentResult"];
            judgeDecision?: components["schemas"]["JudgeDecision"];
            modelInvocations?: components["schemas"]["ModelInvocation"][];
            toolCallAudits?: components["schemas"]["ToolCallAudit"][];
            changedFiles?: string[];
            pendingApproval?: components["schemas"]["ApprovalRequest"];
            iteration?: number;
            maxIterations?: number;
            budget?: components["schemas"]["RunBudget"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            error?: {
                code?: string;
                message?: string;
            };
        } & {
            [key: string]: unknown;
        };
        RunPage: {
            items: components["schemas"]["Run"][];
            nextCursor?: string;
        };
        RunEvent: {
            /** Format: uuid */
            eventId: string;
            /** Format: uuid */
            runId: string;
            /** Format: uuid */
            traceId: string;
            type: string;
            nodeId?: string;
            message: string;
            /** Format: date-time */
            createdAt: string;
        };
        SequencedEvent: {
            /** Format: int64 */
            sequence: number;
            event: components["schemas"]["RunEvent"];
        };
        EventPage: {
            items: components["schemas"]["SequencedEvent"][];
            /** Format: int64 */
            nextCursor: number;
        };
        Approval: {
            request: components["schemas"]["ApprovalRequest"];
            /** Format: int64 */
            runVersion: number;
        };
        ApprovalList: {
            items: components["schemas"]["Approval"][];
        };
        Artifact: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            runId: string;
            /** @enum {string} */
            kind: "patch" | "test_evidence" | "run_report" | "log";
            storageKey: string;
            sha256: string;
            /** Format: int64 */
            size: number;
            contentType: string;
            attributes: {
                [key: string]: string;
            };
            /** Format: date-time */
            createdAt: string;
        };
        ArtifactList: {
            items: components["schemas"]["Artifact"][];
        };
        RunReport: {
            /** Format: uuid */
            runId: string;
            status: components["schemas"]["RunStatus"];
            plan?: components["schemas"]["ExecutionPlan"];
            implementation?: components["schemas"]["ImplementationResult"];
            tests?: components["schemas"]["TestAssessment"];
            review?: components["schemas"]["AssessmentResult"];
            security?: components["schemas"]["AssessmentResult"];
            decision?: components["schemas"]["JudgeDecision"];
            error?: {
                code?: string;
                message?: string;
            };
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            remember?: boolean;
        };
        CreateRepositoryRequest: {
            name: string;
            localPath: string;
            /** @default HEAD */
            defaultBranch: string;
        };
        CreateRunRequest: {
            /** Format: uuid */
            repositoryId: string;
            task: string;
            baseRevision?: string;
            maxIterations?: number;
        };
        RunMutationRequest: {
            reason?: string;
        };
        ApprovalDecision: {
            /** @enum {string} */
            decision: "approve" | "reject";
            comment?: string;
        };
        /** @enum {string} */
        EvalMode: "single_agent" | "planner_developer" | "forgeflow";
        EvalMetrics: {
            completionRate: number;
            hiddenTestPassRate: number;
            regressionRate: number;
            humanInterventionRate: number;
            averageCostUsd?: number | null;
            p95LatencyMs?: number | null;
        };
        EvalConfiguration: {
            mode: components["schemas"]["EvalMode"];
            modelVersions: {
                [key: string]: string;
            };
            promptVersions: {
                [key: string]: string;
            };
            policyVersion: string;
            toolVersions: {
                [key: string]: string;
            };
            gitCommit: string;
        };
        EvalReport: {
            schemaVersion: string;
            dataset: string;
            datasetVersion: string;
            /** Format: date-time */
            generatedAt: string;
            configuration: components["schemas"]["EvalConfiguration"];
            total: number;
            passed: number;
            grades: {
                [key: string]: unknown;
            }[];
            metrics: components["schemas"]["EvalMetrics"];
            unavailableMetrics: string[];
        };
        ComparisonReport: {
            schemaVersion: string;
            dataset: string;
            /** Format: date-time */
            generatedAt: string;
            reports: components["schemas"]["EvalReport"][];
        };
        EvalRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            createdBy: string;
            dataset: string;
            datasetVersion: string;
            /** @enum {string} */
            status: "completed" | "failed";
            report: components["schemas"]["ComparisonReport"];
            /** Format: date-time */
            createdAt: string;
        };
        EvalRunList: {
            items: components["schemas"]["EvalRun"][];
        };
        Observation: {
            caseId: string;
            /** @enum {string} */
            decision: "implement" | "clarify" | "deny" | "require_approval";
            patchApplicable: boolean;
            changedFiles: string[];
            buildPassed: boolean;
            explicitTestsPassed: boolean;
            hiddenTestResults: {
                [key: string]: boolean;
            };
            secretDetected: boolean;
            dangerousCommandExecuted: boolean;
            iterations: number;
            diffLines: number;
            costUsd?: number;
            /** Format: int64 */
            durationMs?: number;
            regression: boolean;
            humanIntervention: boolean;
        } & {
            [key: string]: unknown;
        };
        Evidence: {
            dataset: string;
            configuration: components["schemas"]["EvalConfiguration"];
            /** Format: date-time */
            observedAt: string;
            observations: components["schemas"]["Observation"][];
        };
        EvidenceFile: {
            runs: components["schemas"]["Evidence"][];
        };
        Agent: {
            name: string;
            version: string;
            model: string;
            promptVersion: string;
            role: string;
        };
        AgentList: {
            items: components["schemas"]["Agent"][];
        };
        Prompt: {
            agent: string;
            version: string;
            sha256: string;
            configured: boolean;
        };
        PromptRelease: {
            /** Format: uuid */
            id: string;
            agent: string;
            version: string;
            promptSha256: string;
            model: string;
            /** Format: uuid */
            evalRunId: string;
            /** Format: uuid */
            promotedBy: string;
            /** Format: uuid */
            rollbackOf?: string;
            comment: string;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        PromptCatalog: {
            items: components["schemas"]["Prompt"][];
            releases: components["schemas"]["PromptRelease"][];
        };
        PromptPromotionRequest: {
            /** Format: uuid */
            evalRunId: string;
            comment: string;
        };
        PromptRollbackRequest: {
            /** Format: uuid */
            releaseId: string;
            comment: string;
        };
        Error: {
            code: string;
            message: string;
            requestId: string;
            details: Record<string, never>;
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        CSRF: string;
        Cursor: string;
        EventCursor: number;
        Limit: number;
        RunId: string;
        RepositoryId: string;
        ApprovalId: string;
        SessionId: string;
        EvalRunId: string;
        AgentName: string;
        PromptVersion: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    listRepositories: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repository page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryPage"];
                };
            };
        };
    };
    createRepository: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRepositoryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    getRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repository */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteRepository: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path: {
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validateRepository: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path: {
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repository summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listRunEvents: {
        parameters: {
            query?: {
                after?: components["parameters"]["EventCursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sequenced events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
        };
    };
    streamRunEvents: {
        parameters: {
            query?: {
                after?: components["parameters"]["EventCursor"];
            };
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream; reconnect with Last-Event-ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    pauseRun: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunMutationRequest"];
            };
        };
        responses: {
            /** @description Paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    resumeRun: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunMutationRequest"];
            };
        };
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listRunArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactList"];
                };
            };
        };
    };
    getRunReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunReport"];
                };
            };
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "rejected";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accessible approvals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalList"];
                };
            };
        };
    };
    getApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approvalId: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approval with ETag */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": string;
            };
            path: {
                approvalId: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description Decided */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    listEvalRuns: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored comparison reports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunList"];
                };
            };
        };
    };
    createEvalRun: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceFile"];
            };
        };
        responses: {
            /** @description Graded report */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRun"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getEvalRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evalRunId: components["parameters"]["EvalRunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comparison report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRun"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime agent catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentList"];
                };
            };
        };
    };
    listPrompts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Embedded prompts and immutable release history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptCatalog"];
                };
            };
        };
    };
    promotePrompt: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path: {
                agent: components["parameters"]["AgentName"];
                version: components["parameters"]["PromptVersion"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptPromotionRequest"];
            };
        };
        responses: {
            /** @description Prompt release */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptRelease"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    rollbackPrompt: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path: {
                agent: components["parameters"]["AgentName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptRollbackRequest"];
            };
        };
        responses: {
            /** @description Immutable rollback release */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptRelease"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
}
